#!/bin/sh

# Wrapper to run rofi with blurred background on KDE Plasma.

/usr/bin/rofi $@ & 

c=0
while ! xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $(xdotool search -class 'rofi') 2> /dev/null ; do
    sleep .1
    c=$((c + 1))
    [[ $c = 50 ]] && exit; # Stop script if rofi's window didn't appear after 5 seconds.
done

